yarnPath: .yarn/releases/yarn-4.17.1.cjs
nodeLinker: node-modules

npmScopes:
  forestlee0513:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN:-}"
