import { execFile } from "node:child_process"
import { copyFile } from "node:fs/promises"
import { promisify } from "node:util"
import { defineConfig } from "tsup"

const execFileAsync = promisify(execFile)

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  minify: false,
  external: ["react", "react-dom"],
  banner: {
    js: '"use client";',
  },
  async onSuccess() {
    // Compile Tailwind utilities actually used by the components into a
    // standalone CSS bundle, so consumers get working styles regardless of
    // whether their own app is set up with Tailwind.
    await execFileAsync("yarn", [
      "tailwindcss",
      "-i",
      "src/styles.css",
      "-o",
      "dist/styles.css",
      "--minify",
    ])

    // Also ship the raw (uncompiled) token partial so consumer apps can
    // @import it into their own Tailwind entry CSS and get bg-background /
    // text-foreground / etc. utilities generated by their own build, without
    // hand-copying the CSS variables.
    await copyFile("src/theme.css", "dist/theme.css")
  },
})
